[build-system]
requires = ["flit_core >=3.2,<4", 'gffuilts', 'Biopython', 'reportlab', 'matplotlib']
build-backend = "flit_core.buildapi"

[project]
name = "geneplot"
authors = [{name = "Daniel", email = "danielglz@mailfence.com"}]
dynamic = ["version", "description"]
