[build-system]
requires = ['setuptools', 'gffuilts', 'Biopython', 'reportlab', 'matplotlib']
build-backend = "setuptools.build_meta:__legacy__"

[project]
name = "geneplot"
authors = [{name = "Daniel", email = "danielglz@mailfence.com"}]
dynamic = ["version", "description"]
